# Generated by Django 4.2 on 2023-04-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='null', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
